
; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.0
projects[calendar][subdir] = contrib
projects[calendar][version] = 3.3
projects[captcha][subdir] = contrib
projects[captcha][version] = 1.0-beta2
projects[context][subdir] = contrib
projects[context][version] = 3.0-beta2
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0
projects[date][subdir] = contrib
projects[date][version] = 2.5
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta3
projects[debut_event][subdir] = contrib
projects[debut_event][version] = 1.0-beta7
projects[debut_media][subdir] = contrib
projects[debut_media][version] = 1.0-beta7
projects[features][subdir] = contrib
projects[features][version] = 1.0-rc2
projects[file_entity][subdir] = contrib
projects[file_entity][version] = 2.0-unstable4
projects[media][subdir] = contrib
projects[media][version] = 2.0-unstable4
projects[media_vimeo][subdir] = contrib
projects[media_vimeo][version] = 1.0-beta5
projects[media_youtube][subdir] = contrib
projects[media_youtube][version] = 1.0-beta3
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.0
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0-rc1
projects[styles][subdir] = contrib
projects[styles][version] = 2.0-alpha8
projects[token][subdir] = contrib
projects[token][version] = 1.0
projects[views][subdir] = contrib
projects[views][version] = 3.3


